title: Mahdi Ebsim
position: 
email: msebsim@gmail.com
keywords: mahdi ebsim
avatar: ./assets/img/avatar.png
description: Mahdi Ebsim C.V.
canonical: https://mahdiebsim.github.io/
remote_theme: yaoyao-liu/minimal-light
